### PR TITLE
Add keepalived.conf in controlplane yamls

### PR DESCRIPTION
**Pull request by kashifest**
This PR presents a template for adding keepalived configuration file in control-plane object. 

Co-authored-by: Xenwar <anwar.hassen@est.tech>

### CODE REVIEW

**Comment by maelk** [comment]
postponing until Jan's work is complete and this can be taken into metal3-dev-env

**Comment by Xenwar** [comment]
@kashifest why did you close this issue ?

**Comment by kashifest** [comment]
I don't recall now. someone asked me to check this

**Comment by Xenwar** [comment]
Thanks @kashifest.
@maelk you suggested postponing this PR.
What is the status ?

**Pull request closed without merging**
